releases:
  - name: login_banner
    version: 0+dev.18

addons:
  - name: login_banner
    jobs:
    - name: login_banner
      release: login_banner
    properties:
      login_banner:
        text: |
          Multi
          line
          example
