releases:
  - name: login_banner
    version: <RELEASE VERSION>

addons:
  - name: os-configuration
    jobs:
    - name: tcp_keepalive
      release: os-conf
    - name: login_banner
      release: os-conf
    - name: user_add
      release: os-conf
    properties:
      login_banner:
        text: |
          Multi
          line
          example
      users:
      - name: bob
        crypted_password: "$6$HHH8p917$mZjPv/QkYutmQNkxBqEA2nC08zFBDbB482R0v6FyQfT31FZIqEfDTr024LbPFJWcSrwaEYcaKW75FnqHhLqYR."
      - name: sally
        public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbss5XtLYRYDeV8AmouVYOHmYPxPsN4F59fZnY4kJnimM3sk5TbP0ow19GMDppQOPzAQ1TcYH4sYhpnxwq5f32XYtw12rFnO8BatHISWIdjoEjHfdA1qLIMGouWZPbGIQ1qURbfJdR9e2shS7U/WSXD+AJ9Zy0ZKTsIvlukWSX8Nsxvfn7VaAFvhgI3YPmhjV3TCEVMDsWGbBXlMq+qiJt22JEOw+3dnrvfGzRUULGznO/8y4NvVQsQc5KGnJkeQWkmlOIrhUGYwd/hMn6zQEIxkR4elmwp+pjyLR0qYLUFjpMn2GJMG7lvTzF8SzQLhzTVrjW1E3nve2eCuJ5bB6/"
